### ISSUE TITLE
ArrayGarlandMethods, ArrayGarland

### ISSUE THREAD

**Issue by milkina** [MaksGrishaev/HomeWork#12]
1. garland[i] = (random.nextInt(100)) % 2; - избыточные скобки. Можно:
garland[i] = random.nextInt(100) % 2;
2. 
```
String choice = "a";
...
 choice = sc.next();
```
можно в одной строке объявить и проинициализировать.
2. ArrayGarland - убрать ненужные пустые строки
3. Если можно использовать цикл for each вместо for, используйте его.  Это касается и всех остальных заданий.

**Comment by milkina** [comment]
2. ArrayGarland - убрать ненужные пустые строки
Вместо
```
 ArrayGarlandMethods.garlandChoice(garland);
    }

}
```
должно быть
```
 ArrayGarlandMethods.garlandChoice(garland);
    }
}
```

**Comment by MaksGrishaev** [comment]
+
