### ISSUE TITLE
Matrix

### ISSUE THREAD

**Issue by milkina** [MaksGrishaev/HomeWork#16]
1. Уберите из конструктора вызов cеттеров. Обычно так не делается. Напомните, на уроке это обсудим
2. Вместо         if (zero == true)  лучше         if (zero) {
3. Matrix multMatrix(Matrix matrix2) - можно еще добавить проверку, что размерность строк и столбцов должна быть одинаковая.
4. MyMatrix - убрать ненужный импорт.
5. MyMatrix - преобразовать комментрарий в документирующий.

**Comment by milkina** [comment]
Matrix - тоже убрать ненужный импорт.

**Comment by MaksGrishaev** [comment]
+
